spring.application.name=jackpot-service

spring.datasource.url=jdbc:h2:mem:jackpot_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=none

spring.threads.virtual.enabled=true

spring.kafka.bootstrap-servers=localhost:9092
